# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a  param for original distribution
#' @param b  param for original distribution
#' @param n  param for original distribution
#' @param N the number of samples
#' 
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#' rnC <- gibbsC(1,1,25,10000)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
gibbsC <- function(a, b, n, N) {
    .Call('_StatComp21055_gibbsC', PACKAGE = 'StatComp21055', a, b, n, N)
}

